//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressDeliver
    {
        public int ID { get; set; }
        public string Cus_name { get; set; }
        public string Cus_phone { get; set; }
        public string ApartmentNumber { get; set; }
        public Nullable<int> Default { get; set; }
        public string Ward { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string UserID { get; set; }
        public string WardCode { get; set; }
        public string DistrictCode { get; set; }
        public string CityCode { get; set; }
    
        public virtual User User { get; set; }
    }
}
