//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluate
    {
        public int ID { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Content { get; set; }
        public string CustomerID { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
