//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Galleries = new HashSet<Gallery>();
            this.MyCarts = new HashSet<MyCart>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Product_Category = new HashSet<Product_Category>();
            this.Product_Spec = new HashSet<Product_Spec>();
        }
    
        public int ID { get; set; }
        public string ShopID { get; set; }
        public string Title { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> OldPrice { get; set; }
        public string Image { get; set; }
        public string Video { get; set; }
        public string SortContent { get; set; }
        public string Description { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Sold { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Inventory { get; set; }
        public string StatusProduct { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ApproveStatus { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<int> ParrentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gallery> Galleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyCart> MyCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Category> Product_Category { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Spec> Product_Spec { get; set; }
    }
}
